### ISSUE TITLE
I think you should add a function

### ISSUE THREAD

**Issue by jwjeong-bit** [kjy00302/pylooper#2]
My computer doesn't have speakers and a microphone.
So I got an error line.
OSError : [Errno -9996] Invalid input device (no default output device)
It would be nice to add a function that notifies you before use.
THANK YOU!!

**Comment by jwjeong-bit** [comment]
$ python -m pylooper
pygame 2.0.1 (SDL 2.0.14, Python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Failed to open audio stream
Traceback (most recent call last):
  File "C:\project\practice\pylooper\pylooper\audioworker.py", line 18, in aw_init
    stream_callback=self.aw_callback
  File "C:\Users\정제원\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\정제원\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)

Check your audio device <- I can see notice

**Comment by kjy00302** [comment]
Fixed by 802c8b82660425ae29b907b37d9bcb0201f13e55?
